path: ./data
train: images/train
val: images/val
test: images/test
names:
  0: warning
  1: no parking/waiting
  2: other prohibition signs
  3: no entry
  4: mandatory
  5: max speed
  6: no turning
